optimizer:
  name: adam
  lr: 1.0e-4
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 256
  save_model: true
  loss: pairwise
  test_step: 1
  patience: 10

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf

model:
  keep_rate: 0.8
  embedding_size: 256

  layer_num: 3
  reg_weight: 1.0e-6
  kd_weight: 1.0e-2
  kd_temperature: 0.2
  # for amazon
  amazon:
    layer_num: 3
    reg_weight: 1.0e-6
    kd_weight: 1.0e-2
    kd_temperature: 0.2
  # for yelp
  yelp:
    layer_num: 3
    reg_weight: 1.0e-6
    kd_weight: 1.0e-2
    kd_temperature: 0.2
  # for steam
  steam:
    layer_num: 2
    reg_weight: 1.0e-6
    kd_weight: 1.0e-2
    kd_temperature: 0.2
