optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 300
  batch_size: 256
  save_model: true
  loss: pairwise
  test_step: 1
  patience: 10

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf

model:
  dropout: 0
  layer_num: 2
  cl_weight: 0.1
  reg_weight: 1.0e-9
  temp: 0.1
  embedding_size: 256
  svd_q: 5
